// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.29.0
// 	protoc        v4.22.2
// source: proto/ptadmin.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Task type
type PtTaskType int32

const (
	// Local task type
	PtTaskType_LOCAL PtTaskType = 0
	// Distribution task type
	PtTaskType_DISTRIBUTION PtTaskType = 1
)

// Enum value maps for PtTaskType.
var (
	PtTaskType_name = map[int32]string{
		0: "LOCAL",
		1: "DISTRIBUTION",
	}
	PtTaskType_value = map[string]int32{
		"LOCAL":        0,
		"DISTRIBUTION": 1,
	}
)

func (x PtTaskType) Enum() *PtTaskType {
	p := new(PtTaskType)
	*p = x
	return p
}

func (x PtTaskType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PtTaskType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_ptadmin_proto_enumTypes[0].Descriptor()
}

func (PtTaskType) Type() protoreflect.EnumType {
	return &file_proto_ptadmin_proto_enumTypes[0]
}

func (x PtTaskType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PtTaskType.Descriptor instead.
func (PtTaskType) EnumDescriptor() ([]byte, []int) {
	return file_proto_ptadmin_proto_rawDescGZIP(), []int{0}
}

// Task status
type PtTaskStatus int32

const (
	// Task is pending
	PtTaskStatus_PENDING PtTaskStatus = 0
	// Task is provisioned
	PtTaskStatus_PROVISIONED PtTaskStatus = 1
	// Task is running
	PtTaskStatus_RUNNING PtTaskStatus = 2
	// Task is finished
	PtTaskStatus_FINISHED PtTaskStatus = 3
	// Task is failed
	PtTaskStatus_FAILED PtTaskStatus = 4
)

// Enum value maps for PtTaskStatus.
var (
	PtTaskStatus_name = map[int32]string{
		0: "PENDING",
		1: "PROVISIONED",
		2: "RUNNING",
		3: "FINISHED",
		4: "FAILED",
	}
	PtTaskStatus_value = map[string]int32{
		"PENDING":     0,
		"PROVISIONED": 1,
		"RUNNING":     2,
		"FINISHED":    3,
		"FAILED":      4,
	}
)

func (x PtTaskStatus) Enum() *PtTaskStatus {
	p := new(PtTaskStatus)
	*p = x
	return p
}

func (x PtTaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PtTaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_ptadmin_proto_enumTypes[1].Descriptor()
}

func (PtTaskStatus) Type() protoreflect.EnumType {
	return &file_proto_ptadmin_proto_enumTypes[1]
}

func (x PtTaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PtTaskStatus.Descriptor instead.
func (PtTaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_ptadmin_proto_rawDescGZIP(), []int{1}
}

// Traffic for the task
type PtTaskTracffic struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Region for the traffic
	Region string `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	// Percent for the traffic
	Pecent int32 `protobuf:"varint,2,opt,name=pecent,proto3" json:"pecent,omitempty"`
}

func (x *PtTaskTracffic) Reset() {
	*x = PtTaskTracffic{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ptadmin_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PtTaskTracffic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PtTaskTracffic) ProtoMessage() {}

func (x *PtTaskTracffic) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ptadmin_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PtTaskTracffic.ProtoReflect.Descriptor instead.
func (*PtTaskTracffic) Descriptor() ([]byte, []int) {
	return file_proto_ptadmin_proto_rawDescGZIP(), []int{0}
}

func (x *PtTaskTracffic) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *PtTaskTracffic) GetPecent() int32 {
	if x != nil {
		return x.Pecent
	}
	return 0
}

// Scripts for the task
type PtTaskScript struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Script name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Script type: file, zip, gz, tar, etc; "file is default"
	Type *string `protobuf:"bytes,2,opt,name=type,proto3,oneof" json:"type,omitempty"`
	// Script content
	Data []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *PtTaskScript) Reset() {
	*x = PtTaskScript{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ptadmin_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PtTaskScript) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PtTaskScript) ProtoMessage() {}

func (x *PtTaskScript) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ptadmin_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PtTaskScript.ProtoReflect.Descriptor instead.
func (*PtTaskScript) Descriptor() ([]byte, []int) {
	return file_proto_ptadmin_proto_rawDescGZIP(), []int{1}
}

func (x *PtTaskScript) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PtTaskScript) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *PtTaskScript) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Task for performance test
type PtTask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Total users to be stimulated in test
	TotalUsers int32 `protobuf:"varint,1,opt,name=total_users,json=totalUsers,proto3" json:"total_users,omitempty"`
	// Duration for test
	Duration int32 `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"`
	// Ramp up time for test
	RampUp int32 `protobuf:"varint,3,opt,name=ramp_up,json=rampUp,proto3" json:"ramp_up,omitempty"`
	// Task type for perforamnce test: Local, or Distribution
	Type PtTaskType `protobuf:"varint,4,opt,name=type,proto3,enum=PtTaskType" json:"type,omitempty"`
	// Traffics arragement
	Traffics []*PtTaskTracffic `protobuf:"bytes,10,rep,name=traffics,proto3" json:"traffics,omitempty"`
}

func (x *PtTask) Reset() {
	*x = PtTask{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ptadmin_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PtTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PtTask) ProtoMessage() {}

func (x *PtTask) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ptadmin_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PtTask.ProtoReflect.Descriptor instead.
func (*PtTask) Descriptor() ([]byte, []int) {
	return file_proto_ptadmin_proto_rawDescGZIP(), []int{2}
}

func (x *PtTask) GetTotalUsers() int32 {
	if x != nil {
		return x.TotalUsers
	}
	return 0
}

func (x *PtTask) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *PtTask) GetRampUp() int32 {
	if x != nil {
		return x.RampUp
	}
	return 0
}

func (x *PtTask) GetType() PtTaskType {
	if x != nil {
		return x.Type
	}
	return PtTaskType_LOCAL
}

func (x *PtTask) GetTraffics() []*PtTaskTracffic {
	if x != nil {
		return x.Traffics
	}
	return nil
}

// Launched Task for performance test with status and links
type PtLaunchedTask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Task id
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Task
	Task *PtTask `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
	// Task status
	Status PtTaskStatus `protobuf:"varint,3,opt,name=status,proto3,enum=PtTaskStatus" json:"status,omitempty"`
	// Created time
	Created *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created,proto3" json:"created,omitempty"`
	// Finished time
	Finished *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=finished,proto3" json:"finished,omitempty"`
	// last updated time
	LastUpdated *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	// Link to metrics dashboard
	MetricsLink string `protobuf:"bytes,10,opt,name=metrics_link,json=metricsLink,proto3" json:"metrics_link,omitempty"`
	// Link to logs
	LogsLink string `protobuf:"bytes,11,opt,name=logs_link,json=logsLink,proto3" json:"logs_link,omitempty"`
	// Link to download the test results
	DownloadLink string `protobuf:"bytes,12,opt,name=download_link,json=downloadLink,proto3" json:"download_link,omitempty"`
}

func (x *PtLaunchedTask) Reset() {
	*x = PtLaunchedTask{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ptadmin_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PtLaunchedTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PtLaunchedTask) ProtoMessage() {}

func (x *PtLaunchedTask) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ptadmin_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PtLaunchedTask.ProtoReflect.Descriptor instead.
func (*PtLaunchedTask) Descriptor() ([]byte, []int) {
	return file_proto_ptadmin_proto_rawDescGZIP(), []int{3}
}

func (x *PtLaunchedTask) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PtLaunchedTask) GetTask() *PtTask {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *PtLaunchedTask) GetStatus() PtTaskStatus {
	if x != nil {
		return x.Status
	}
	return PtTaskStatus_PENDING
}

func (x *PtLaunchedTask) GetCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.Created
	}
	return nil
}

func (x *PtLaunchedTask) GetFinished() *timestamppb.Timestamp {
	if x != nil {
		return x.Finished
	}
	return nil
}

func (x *PtLaunchedTask) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

func (x *PtLaunchedTask) GetMetricsLink() string {
	if x != nil {
		return x.MetricsLink
	}
	return ""
}

func (x *PtLaunchedTask) GetLogsLink() string {
	if x != nil {
		return x.LogsLink
	}
	return ""
}

func (x *PtLaunchedTask) GetDownloadLink() string {
	if x != nil {
		return x.DownloadLink
	}
	return ""
}

// Task list for performance test
type PtTaskList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Task to be created
	LaunchedTasks []*PtLaunchedTask `protobuf:"bytes,1,rep,name=launched_tasks,json=launchedTasks,proto3" json:"launched_tasks,omitempty"`
}

func (x *PtTaskList) Reset() {
	*x = PtTaskList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ptadmin_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PtTaskList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PtTaskList) ProtoMessage() {}

func (x *PtTaskList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ptadmin_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PtTaskList.ProtoReflect.Descriptor instead.
func (*PtTaskList) Descriptor() ([]byte, []int) {
	return file_proto_ptadmin_proto_rawDescGZIP(), []int{4}
}

func (x *PtTaskList) GetLaunchedTasks() []*PtLaunchedTask {
	if x != nil {
		return x.LaunchedTasks
	}
	return nil
}

var File_proto_ptadmin_proto protoreflect.FileDescriptor

var file_proto_ptadmin_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x74, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x40, 0x0a, 0x0e, 0x50, 0x74, 0x54, 0x61, 0x73, 0x6b,
	0x54, 0x72, 0x61, 0x63, 0x66, 0x66, 0x69, 0x63, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x67, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e,
	0x12, 0x16, 0x0a, 0x06, 0x70, 0x65, 0x63, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x70, 0x65, 0x63, 0x65, 0x6e, 0x74, 0x22, 0x58, 0x0a, 0x0c, 0x50, 0x74, 0x54, 0x61,
	0x73, 0x6b, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x17, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x88, 0x01, 0x01, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x22, 0xac, 0x01, 0x0a, 0x06, 0x50, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x1f, 0x0a,
	0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x73, 0x12, 0x1a,
	0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x61,
	0x6d, 0x70, 0x5f, 0x75, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x61, 0x6d,
	0x70, 0x55, 0x70, 0x12, 0x1f, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x0b, 0x2e, 0x50, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x2b, 0x0a, 0x08, 0x74, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63, 0x73,
	0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x50, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x54,
	0x72, 0x61, 0x63, 0x66, 0x66, 0x69, 0x63, 0x52, 0x08, 0x74, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63,
	0x73, 0x22, 0xf6, 0x02, 0x0a, 0x0e, 0x50, 0x74, 0x4c, 0x61, 0x75, 0x6e, 0x63, 0x68, 0x65, 0x64,
	0x54, 0x61, 0x73, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x07, 0x2e, 0x50, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x04, 0x74, 0x61, 0x73,
	0x6b, 0x12, 0x25, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x0d, 0x2e, 0x50, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x34, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x12, 0x36,
	0x0a, 0x08, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x08, 0x66, 0x69,
	0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x12, 0x3d, 0x0a, 0x0c, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0b, 0x6c, 0x61, 0x73, 0x74, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73,
	0x5f, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6d, 0x65, 0x74,
	0x72, 0x69, 0x63, 0x73, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x6f, 0x67, 0x73,
	0x5f, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f, 0x67,
	0x73, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x23, 0x0a, 0x0d, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61,
	0x64, 0x5f, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x64, 0x6f,
	0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x4c, 0x69, 0x6e, 0x6b, 0x22, 0x44, 0x0a, 0x0a, 0x50, 0x74,
	0x54, 0x61, 0x73, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x36, 0x0a, 0x0e, 0x6c, 0x61, 0x75, 0x6e,
	0x63, 0x68, 0x65, 0x64, 0x5f, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x50, 0x74, 0x4c, 0x61, 0x75, 0x6e, 0x63, 0x68, 0x65, 0x64, 0x54, 0x61, 0x73,
	0x6b, 0x52, 0x0d, 0x6c, 0x61, 0x75, 0x6e, 0x63, 0x68, 0x65, 0x64, 0x54, 0x61, 0x73, 0x6b, 0x73,
	0x2a, 0x29, 0x0a, 0x0a, 0x50, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09,
	0x0a, 0x05, 0x4c, 0x4f, 0x43, 0x41, 0x4c, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x44, 0x49, 0x53,
	0x54, 0x52, 0x49, 0x42, 0x55, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x01, 0x2a, 0x53, 0x0a, 0x0c, 0x50,
	0x74, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x50,
	0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x50, 0x52, 0x4f, 0x56,
	0x49, 0x53, 0x49, 0x4f, 0x4e, 0x45, 0x44, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x55, 0x4e,
	0x4e, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x46, 0x49, 0x4e, 0x49, 0x53, 0x48,
	0x45, 0x44, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x04,
	0x42, 0x06, 0x5a, 0x04, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_ptadmin_proto_rawDescOnce sync.Once
	file_proto_ptadmin_proto_rawDescData = file_proto_ptadmin_proto_rawDesc
)

func file_proto_ptadmin_proto_rawDescGZIP() []byte {
	file_proto_ptadmin_proto_rawDescOnce.Do(func() {
		file_proto_ptadmin_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_ptadmin_proto_rawDescData)
	})
	return file_proto_ptadmin_proto_rawDescData
}

var file_proto_ptadmin_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_ptadmin_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_ptadmin_proto_goTypes = []interface{}{
	(PtTaskType)(0),               // 0: PtTaskType
	(PtTaskStatus)(0),             // 1: PtTaskStatus
	(*PtTaskTracffic)(nil),        // 2: PtTaskTracffic
	(*PtTaskScript)(nil),          // 3: PtTaskScript
	(*PtTask)(nil),                // 4: PtTask
	(*PtLaunchedTask)(nil),        // 5: PtLaunchedTask
	(*PtTaskList)(nil),            // 6: PtTaskList
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_proto_ptadmin_proto_depIdxs = []int32{
	0, // 0: PtTask.type:type_name -> PtTaskType
	2, // 1: PtTask.traffics:type_name -> PtTaskTracffic
	4, // 2: PtLaunchedTask.task:type_name -> PtTask
	1, // 3: PtLaunchedTask.status:type_name -> PtTaskStatus
	7, // 4: PtLaunchedTask.created:type_name -> google.protobuf.Timestamp
	7, // 5: PtLaunchedTask.finished:type_name -> google.protobuf.Timestamp
	7, // 6: PtLaunchedTask.last_updated:type_name -> google.protobuf.Timestamp
	5, // 7: PtTaskList.launched_tasks:type_name -> PtLaunchedTask
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_proto_ptadmin_proto_init() }
func file_proto_ptadmin_proto_init() {
	if File_proto_ptadmin_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_ptadmin_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PtTaskTracffic); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ptadmin_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PtTaskScript); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ptadmin_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PtTask); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ptadmin_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PtLaunchedTask); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ptadmin_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PtTaskList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_ptadmin_proto_msgTypes[1].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_ptadmin_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_ptadmin_proto_goTypes,
		DependencyIndexes: file_proto_ptadmin_proto_depIdxs,
		EnumInfos:         file_proto_ptadmin_proto_enumTypes,
		MessageInfos:      file_proto_ptadmin_proto_msgTypes,
	}.Build()
	File_proto_ptadmin_proto = out.File
	file_proto_ptadmin_proto_rawDesc = nil
	file_proto_ptadmin_proto_goTypes = nil
	file_proto_ptadmin_proto_depIdxs = nil
}
