apiVersion: v1
kind: Pod 
metadata:
  name: locust-worker1
spec:
  terminationGracePeriodSeconds: 30
  restartPolicy: Never
  containers:
  - name: locust-worker1 
    image:  asia-docker.pkg.dev/play-api-service/test-images/locust-worker
    imagePullPolicy: Always
    command:
    - "locust"
    args:
    - "--worker"
    - "--master-host"
    - "locust-master"
    - "--master-port"
    - "5557"
    - "--loglevel"
    - "DEBUG"
    - "--exit-code-on-error"
    - "0"
    resources:
      requests: 
        cpu: 500m
        memory: 1024Mi


