
apiVersion: v1
kind: Pod 
metadata:
  name: test-ctl
spec:
  terminationGracePeriodSeconds: 30
  restartPolicy: Never
  containers:
  - name: test-ctl
    image:  asia-docker.pkg.dev/play-api-service/test-images/taurus-base
    imagePullPolicy: Always
    command:
    - sh
    - -c 
    - |
     while sleep 1
     do
      echo $?
     done
    ports:
      - name: tcp
        containerPort: 5557
    resources:
      requests: 
        cpu: 500m
        memory: 1024Mi
    volumeMounts:
      - mountPath: /taurus-logs
        name: bzt-pvc
  volumes:
    - name: bzt-pvc
      persistentVolumeClaim:
       claimName: bzt-filestore-pvc


