apiVersion: v1
kind: Pod
metadata:
  labels:
    app: locust-worker
    module: performance-testing
    scenario: test-example
  name: locust-worker-test-example-1
  namespace: default
spec:
  containers:
  - args:
    - --worker
    - --master-host
    - 10.33.0.88
    - --master-port
    - "5557"
    - --loglevel
    - DEBUG
    - --exit-code-on-error
    - "0"
    - --logfile
    - /tmp/worker.log
    command:
    - locust
    image: asia-docker.pkg.dev/play-api-service/test-images/locust-worker
    imagePullPolicy: Always
    name: locust-worker-test-example-1
    readinessProbe:
      exec:
        command:
        - grep
        - | 
          locust.main: Connected to locust master
        - /tmp/worker.log
      failureThreshold: 50
      initialDelaySeconds: 5
      periodSeconds: 30
      successThreshold: 1
      timeoutSeconds: 5
    resources:
      limits:
        cpu: "1"
        ephemeral-storage: 1Gi
        memory: 2Gi
      requests:
        cpu: "1"
        ephemeral-storage: 1Gi
        memory: 2Gi
    securityContext:
      capabilities:
        drop:
        - NET_RAW
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-9qsfc
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Never
  schedulerName: gke.io/optimize-utilization-scheduler
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  - effect: NoSchedule
    key: kubernetes.io/arch
    operator: Equal
    value: amd64
  volumes:
  - name: kube-api-access-9qsfc
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace

