apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: perf-test
build:
  platforms: ["linux/amd64"]
  artifacts:
  - image: asia-docker.pkg.dev/play-api-service/test-images/locust-worker
    context: locust
    docker:
      dockerfile: Dockerfile
  - image: asia-docker.pkg.dev/play-api-service/test-images/taurus-base
    context: taurus
    docker:
      dockerfile: Dockerfile
  - image: asia-docker.pkg.dev/play-api-service/test-images/pt-admin
    context: pt-admin
    docker:
      dockerfile: Dockerfile

manifests:
  kustomize:
    paths:
    - pt-operator/config/crd
  rawYaml: 
    - pt-admin/cloudrun-service.yaml

deploy:
  cloudrun:
    projectid: play-api-service
    region: asia-northeast1

profiles:
- name: default
  manifests:
    kustomize:
      paths:
      - pt-operator/config/default
- name: manager
  manifests:
    kustomize:
      paths:
      - test-operator/config/manager
- name: prometheus
  manifests:
    kustomize:
      paths:
      - pt-operator/config/prometheus
- name: rbac
  manifests:
    kustomize:
      paths:
      - test-operator/config/rbac
- name: samples
  manifests:
    kustomize:
      paths:
      - test-operator/config/samples
