apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: perf-test
build:
  platforms: ["linux/amd64"]
  artifacts:
  - image: asia-docker.pkg.dev/play-api-service/test-images/locust-worker
    context: locust
    docker:
      dockerfile: Dockerfile
  - image: asia-docker.pkg.dev/play-api-service/test-images/taurus-base
    context: taurus
    docker:
      dockerfile: Dockerfile
  #   requires:
  #     - image: asia-docker.pkg.dev/play-api-service/test-images/taurus
  #       alias: v1
  # - image: asia-docker.pkg.dev/play-api-service/test-images/taurus
  #   context: taurus
  #   docker:
  #     dockerfile: Dockerfile.taurus
manifests:
  kustomize:
    paths:
    - test-operator/config/crd
profiles:
- name: default
  manifests:
    kustomize:
      paths:
      - test-operator/config/default
- name: manager
  manifests:
    kustomize:
      paths:
      - test-operator/config/manager
- name: prometheus
  manifests:
    kustomize:
      paths:
      - test-operator/config/prometheus
- name: rbac
  manifests:
    kustomize:
      paths:
      - test-operator/config/rbac
- name: samples
  manifests:
    kustomize:
      paths:
      - test-operator/config/samples
