apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: bzt-filestore-sc
provisioner: filestore.csi.storage.gke.io
volumeBindingMode: Immediate
allowVolumeExpansion: true
reclaimPolicy: Delete
parameters:
  tier: standard
  network: ${NETWORK}
