// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.29.0
// 	protoc        v4.22.2
// source: proto/ptadmin.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Task type
type PtTaskType int32

const (
	// Local task type
	PtTaskType_LOCAL PtTaskType = 0
	// Distribution task type
	PtTaskType_DISTRIBUTION PtTaskType = 1
)

// Enum value maps for PtTaskType.
var (
	PtTaskType_name = map[int32]string{
		0: "LOCAL",
		1: "DISTRIBUTION",
	}
	PtTaskType_value = map[string]int32{
		"LOCAL":        0,
		"DISTRIBUTION": 1,
	}
)

func (x PtTaskType) Enum() *PtTaskType {
	p := new(PtTaskType)
	*p = x
	return p
}

func (x PtTaskType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PtTaskType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_ptadmin_proto_enumTypes[0].Descriptor()
}

func (PtTaskType) Type() protoreflect.EnumType {
	return &file_proto_ptadmin_proto_enumTypes[0]
}

func (x PtTaskType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PtTaskType.Descriptor instead.
func (PtTaskType) EnumDescriptor() ([]byte, []int) {
	return file_proto_ptadmin_proto_rawDescGZIP(), []int{0}
}

// Task status
type PtLaunchedTaskStatus int32

const (
	// Task is pending
	PtLaunchedTaskStatus_PENDING PtLaunchedTaskStatus = 0
	// Task is running
	PtLaunchedTaskStatus_RUNNING PtLaunchedTaskStatus = 1
	// Task is finished
	PtLaunchedTaskStatus_FINISHED PtLaunchedTaskStatus = 2
	// Task is failed
	PtLaunchedTaskStatus_FAILED PtLaunchedTaskStatus = 3
	// Task is failed
	PtLaunchedTaskStatus_CENCELED PtLaunchedTaskStatus = 4
)

// Enum value maps for PtLaunchedTaskStatus.
var (
	PtLaunchedTaskStatus_name = map[int32]string{
		0: "PENDING",
		1: "RUNNING",
		2: "FINISHED",
		3: "FAILED",
		4: "CENCELED",
	}
	PtLaunchedTaskStatus_value = map[string]int32{
		"PENDING":  0,
		"RUNNING":  1,
		"FINISHED": 2,
		"FAILED":   3,
		"CENCELED": 4,
	}
)

func (x PtLaunchedTaskStatus) Enum() *PtLaunchedTaskStatus {
	p := new(PtLaunchedTaskStatus)
	*p = x
	return p
}

func (x PtLaunchedTaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PtLaunchedTaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_ptadmin_proto_enumTypes[1].Descriptor()
}

func (PtLaunchedTaskStatus) Type() protoreflect.EnumType {
	return &file_proto_ptadmin_proto_enumTypes[1]
}

func (x PtLaunchedTaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PtLaunchedTaskStatus.Descriptor instead.
func (PtLaunchedTaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_ptadmin_proto_rawDescGZIP(), []int{1}
}

// Status of provisioning workflow
type StatusWorkflow int32

const (
	// Workflow is provisioning
	StatusWorkflow_PROVISIONING StatusWorkflow = 0
	// Workflow is provisioning finished
	StatusWorkflow_PROVISIONING_FINISHED StatusWorkflow = 1
	// Workflow is provisioning failed
	StatusWorkflow_PROVISIONING_FAILED StatusWorkflow = 2
)

// Enum value maps for StatusWorkflow.
var (
	StatusWorkflow_name = map[int32]string{
		0: "PROVISIONING",
		1: "PROVISIONING_FINISHED",
		2: "PROVISIONING_FAILED",
	}
	StatusWorkflow_value = map[string]int32{
		"PROVISIONING":          0,
		"PROVISIONING_FINISHED": 1,
		"PROVISIONING_FAILED":   2,
	}
)

func (x StatusWorkflow) Enum() *StatusWorkflow {
	p := new(StatusWorkflow)
	*p = x
	return p
}

func (x StatusWorkflow) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusWorkflow) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_ptadmin_proto_enumTypes[2].Descriptor()
}

func (StatusWorkflow) Type() protoreflect.EnumType {
	return &file_proto_ptadmin_proto_enumTypes[2]
}

func (x StatusWorkflow) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusWorkflow.Descriptor instead.
func (StatusWorkflow) EnumDescriptor() ([]byte, []int) {
	return file_proto_ptadmin_proto_rawDescGZIP(), []int{2}
}

// Traffic for the task
type PtTaskRequestTracffic struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Region for the traffic
	Region string `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	// Percent for the traffic
	Pecent int32 `protobuf:"varint,2,opt,name=pecent,proto3" json:"pecent,omitempty"`
}

func (x *PtTaskRequestTracffic) Reset() {
	*x = PtTaskRequestTracffic{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ptadmin_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PtTaskRequestTracffic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PtTaskRequestTracffic) ProtoMessage() {}

func (x *PtTaskRequestTracffic) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ptadmin_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PtTaskRequestTracffic.ProtoReflect.Descriptor instead.
func (*PtTaskRequestTracffic) Descriptor() ([]byte, []int) {
	return file_proto_ptadmin_proto_rawDescGZIP(), []int{0}
}

func (x *PtTaskRequestTracffic) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *PtTaskRequestTracffic) GetPecent() int32 {
	if x != nil {
		return x.Pecent
	}
	return 0
}

// Scripts for the task
type PtTaskRequestScript struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Script name
	Name *string `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	// Script type: file, zip, gz, tar, etc; "file is default"
	Type *string `protobuf:"bytes,2,opt,name=type,proto3,oneof" json:"type,omitempty"`
	// Script content
	Data string `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *PtTaskRequestScript) Reset() {
	*x = PtTaskRequestScript{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ptadmin_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PtTaskRequestScript) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PtTaskRequestScript) ProtoMessage() {}

func (x *PtTaskRequestScript) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ptadmin_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PtTaskRequestScript.ProtoReflect.Descriptor instead.
func (*PtTaskRequestScript) Descriptor() ([]byte, []int) {
	return file_proto_ptadmin_proto_rawDescGZIP(), []int{1}
}

func (x *PtTaskRequestScript) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *PtTaskRequestScript) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *PtTaskRequestScript) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

// Task for performance test
type PtTaskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Total users to be stimulated in test
	TotalUsers int32 `protobuf:"varint,1,opt,name=total_users,json=totalUsers,proto3" json:"total_users,omitempty"`
	// Duration for test
	Duration int32 `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"`
	// Ramp up time for test
	RampUp int32 `protobuf:"varint,3,opt,name=ramp_up,json=rampUp,proto3" json:"ramp_up,omitempty"`
	// The url of target site
	TargetUrl *string `protobuf:"bytes,4,opt,name=target_url,json=targetUrl,proto3,oneof" json:"target_url,omitempty"`
	// Task type for perforamnce test: Local, or Distribution
	Type PtTaskType `protobuf:"varint,6,opt,name=type,proto3,enum=PtTaskType" json:"type,omitempty"`
	// Traffics arragement
	Traffics []*PtTaskRequestTracffic `protobuf:"bytes,10,rep,name=traffics,proto3" json:"traffics,omitempty"`
	// Scripts for the task
	Scripts *PtTaskRequestScript `protobuf:"bytes,20,opt,name=scripts,proto3" json:"scripts,omitempty"`
}

func (x *PtTaskRequest) Reset() {
	*x = PtTaskRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ptadmin_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PtTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PtTaskRequest) ProtoMessage() {}

func (x *PtTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ptadmin_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PtTaskRequest.ProtoReflect.Descriptor instead.
func (*PtTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_ptadmin_proto_rawDescGZIP(), []int{2}
}

func (x *PtTaskRequest) GetTotalUsers() int32 {
	if x != nil {
		return x.TotalUsers
	}
	return 0
}

func (x *PtTaskRequest) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *PtTaskRequest) GetRampUp() int32 {
	if x != nil {
		return x.RampUp
	}
	return 0
}

func (x *PtTaskRequest) GetTargetUrl() string {
	if x != nil && x.TargetUrl != nil {
		return *x.TargetUrl
	}
	return ""
}

func (x *PtTaskRequest) GetType() PtTaskType {
	if x != nil {
		return x.Type
	}
	return PtTaskType_LOCAL
}

func (x *PtTaskRequest) GetTraffics() []*PtTaskRequestTracffic {
	if x != nil {
		return x.Traffics
	}
	return nil
}

func (x *PtTaskRequest) GetScripts() *PtTaskRequestScript {
	if x != nil {
		return x.Scripts
	}
	return nil
}

// Launched Task for performance test with status and links
type PtLaunchedTask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Task id
	CorrelationId string `protobuf:"bytes,1,opt,name=correlationId,proto3" json:"correlationId,omitempty"`
	// Task
	Task *PtTaskRequest `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
	// Task status
	TaskStatus PtLaunchedTaskStatus `protobuf:"varint,3,opt,name=task_status,json=taskStatus,proto3,enum=PtLaunchedTaskStatus" json:"task_status,omitempty"`
	// Status of provisioning workflow
	ProvisionStatus StatusWorkflow `protobuf:"varint,4,opt,name=provision_status,json=provisionStatus,proto3,enum=StatusWorkflow" json:"provision_status,omitempty"`
	// Created time
	Created *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created,proto3" json:"created,omitempty"`
	// Finished time
	Finished *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=finished,proto3,oneof" json:"finished,omitempty"`
	// last updated time
	LastUpdated *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=last_updated,json=lastUpdated,proto3,oneof" json:"last_updated,omitempty"`
	// Link to metrics dashboard
	MetricsLink *string `protobuf:"bytes,10,opt,name=metrics_link,json=metricsLink,proto3,oneof" json:"metrics_link,omitempty"`
	// Link to logs
	LogsLink *string `protobuf:"bytes,11,opt,name=logs_link,json=logsLink,proto3,oneof" json:"logs_link,omitempty"`
	// Link to download the test results
	DownloadLink *string `protobuf:"bytes,12,opt,name=download_link,json=downloadLink,proto3,oneof" json:"download_link,omitempty"`
}

func (x *PtLaunchedTask) Reset() {
	*x = PtLaunchedTask{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ptadmin_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PtLaunchedTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PtLaunchedTask) ProtoMessage() {}

func (x *PtLaunchedTask) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ptadmin_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PtLaunchedTask.ProtoReflect.Descriptor instead.
func (*PtLaunchedTask) Descriptor() ([]byte, []int) {
	return file_proto_ptadmin_proto_rawDescGZIP(), []int{3}
}

func (x *PtLaunchedTask) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *PtLaunchedTask) GetTask() *PtTaskRequest {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *PtLaunchedTask) GetTaskStatus() PtLaunchedTaskStatus {
	if x != nil {
		return x.TaskStatus
	}
	return PtLaunchedTaskStatus_PENDING
}

func (x *PtLaunchedTask) GetProvisionStatus() StatusWorkflow {
	if x != nil {
		return x.ProvisionStatus
	}
	return StatusWorkflow_PROVISIONING
}

func (x *PtLaunchedTask) GetCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.Created
	}
	return nil
}

func (x *PtLaunchedTask) GetFinished() *timestamppb.Timestamp {
	if x != nil {
		return x.Finished
	}
	return nil
}

func (x *PtLaunchedTask) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

func (x *PtLaunchedTask) GetMetricsLink() string {
	if x != nil && x.MetricsLink != nil {
		return *x.MetricsLink
	}
	return ""
}

func (x *PtLaunchedTask) GetLogsLink() string {
	if x != nil && x.LogsLink != nil {
		return *x.LogsLink
	}
	return ""
}

func (x *PtLaunchedTask) GetDownloadLink() string {
	if x != nil && x.DownloadLink != nil {
		return *x.DownloadLink
	}
	return ""
}

// Task list for performance test
type PtLaunchedTaskList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Task to be created
	LaunchedTasks []*PtLaunchedTask `protobuf:"bytes,1,rep,name=launched_tasks,json=launchedTasks,proto3" json:"launched_tasks,omitempty"`
}

func (x *PtLaunchedTaskList) Reset() {
	*x = PtLaunchedTaskList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ptadmin_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PtLaunchedTaskList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PtLaunchedTaskList) ProtoMessage() {}

func (x *PtLaunchedTaskList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ptadmin_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PtLaunchedTaskList.ProtoReflect.Descriptor instead.
func (*PtLaunchedTaskList) Descriptor() ([]byte, []int) {
	return file_proto_ptadmin_proto_rawDescGZIP(), []int{4}
}

func (x *PtLaunchedTaskList) GetLaunchedTasks() []*PtLaunchedTask {
	if x != nil {
		return x.LaunchedTasks
	}
	return nil
}

var File_proto_ptadmin_proto protoreflect.FileDescriptor

var file_proto_ptadmin_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x74, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x47, 0x0a, 0x15, 0x50, 0x74, 0x54, 0x61, 0x73, 0x6b,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x54, 0x72, 0x61, 0x63, 0x66, 0x66, 0x69, 0x63, 0x12,
	0x16, 0x0a, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x65, 0x63, 0x65, 0x6e,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x70, 0x65, 0x63, 0x65, 0x6e, 0x74, 0x22,
	0x6d, 0x0a, 0x13, 0x50, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x12, 0x17, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x88, 0x01, 0x01, 0x12,
	0x17, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x88, 0x01, 0x01, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x07, 0x0a, 0x05,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x22, 0x9d,
	0x02, 0x0a, 0x0d, 0x50, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x55, 0x73, 0x65, 0x72,
	0x73, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x17, 0x0a,
	0x07, 0x72, 0x61, 0x6d, 0x70, 0x5f, 0x75, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x72, 0x61, 0x6d, 0x70, 0x55, 0x70, 0x12, 0x22, 0x0a, 0x0a, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x5f, 0x75, 0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x09, 0x74, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x55, 0x72, 0x6c, 0x88, 0x01, 0x01, 0x12, 0x1f, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x50, 0x74, 0x54, 0x61, 0x73,
	0x6b, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x32, 0x0a, 0x08, 0x74,
	0x72, 0x61, 0x66, 0x66, 0x69, 0x63, 0x73, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x50, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x54, 0x72, 0x61,
	0x63, 0x66, 0x66, 0x69, 0x63, 0x52, 0x08, 0x74, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63, 0x73, 0x12,
	0x2e, 0x0a, 0x07, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x73, 0x18, 0x14, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x50, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x52, 0x07, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x73, 0x42,
	0x0d, 0x0a, 0x0b, 0x5f, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x75, 0x72, 0x6c, 0x22, 0xc8,
	0x04, 0x0a, 0x0e, 0x50, 0x74, 0x4c, 0x61, 0x75, 0x6e, 0x63, 0x68, 0x65, 0x64, 0x54, 0x61, 0x73,
	0x6b, 0x12, 0x24, 0x0a, 0x0d, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x50, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x12, 0x36, 0x0a, 0x0b, 0x74,
	0x61, 0x73, 0x6b, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x15, 0x2e, 0x50, 0x74, 0x4c, 0x61, 0x75, 0x6e, 0x63, 0x68, 0x65, 0x64, 0x54, 0x61, 0x73,
	0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0a, 0x74, 0x61, 0x73, 0x6b, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x3a, 0x0a, 0x10, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e,
	0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x57, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x52, 0x0f,
	0x70, 0x72, 0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x34, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x07, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x12, 0x3b, 0x0a, 0x08, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65,
	0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x48, 0x00, 0x52, 0x08, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x88,
	0x01, 0x01, 0x12, 0x42, 0x0a, 0x0c, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x48, 0x01, 0x52, 0x0b, 0x6c, 0x61, 0x73, 0x74, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x64, 0x88, 0x01, 0x01, 0x12, 0x26, 0x0a, 0x0c, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63,
	0x73, 0x5f, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x0b,
	0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x4c, 0x69, 0x6e, 0x6b, 0x88, 0x01, 0x01, 0x12, 0x20,
	0x0a, 0x09, 0x6c, 0x6f, 0x67, 0x73, 0x5f, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x0b, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x03, 0x52, 0x08, 0x6c, 0x6f, 0x67, 0x73, 0x4c, 0x69, 0x6e, 0x6b, 0x88, 0x01, 0x01,
	0x12, 0x28, 0x0a, 0x0d, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x6c, 0x69, 0x6e,
	0x6b, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x48, 0x04, 0x52, 0x0c, 0x64, 0x6f, 0x77, 0x6e, 0x6c,
	0x6f, 0x61, 0x64, 0x4c, 0x69, 0x6e, 0x6b, 0x88, 0x01, 0x01, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x66,
	0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x6c, 0x61, 0x73, 0x74,
	0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x6d, 0x65, 0x74,
	0x72, 0x69, 0x63, 0x73, 0x5f, 0x6c, 0x69, 0x6e, 0x6b, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x6c, 0x6f,
	0x67, 0x73, 0x5f, 0x6c, 0x69, 0x6e, 0x6b, 0x42, 0x10, 0x0a, 0x0e, 0x5f, 0x64, 0x6f, 0x77, 0x6e,
	0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x6c, 0x69, 0x6e, 0x6b, 0x22, 0x4c, 0x0a, 0x12, 0x50, 0x74, 0x4c,
	0x61, 0x75, 0x6e, 0x63, 0x68, 0x65, 0x64, 0x54, 0x61, 0x73, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x36, 0x0a, 0x0e, 0x6c, 0x61, 0x75, 0x6e, 0x63, 0x68, 0x65, 0x64, 0x5f, 0x74, 0x61, 0x73, 0x6b,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x50, 0x74, 0x4c, 0x61, 0x75, 0x6e,
	0x63, 0x68, 0x65, 0x64, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x0d, 0x6c, 0x61, 0x75, 0x6e, 0x63, 0x68,
	0x65, 0x64, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x2a, 0x29, 0x0a, 0x0a, 0x50, 0x74, 0x54, 0x61, 0x73,
	0x6b, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x4c, 0x4f, 0x43, 0x41, 0x4c, 0x10, 0x00,
	0x12, 0x10, 0x0a, 0x0c, 0x44, 0x49, 0x53, 0x54, 0x52, 0x49, 0x42, 0x55, 0x54, 0x49, 0x4f, 0x4e,
	0x10, 0x01, 0x2a, 0x58, 0x0a, 0x14, 0x50, 0x74, 0x4c, 0x61, 0x75, 0x6e, 0x63, 0x68, 0x65, 0x64,
	0x54, 0x61, 0x73, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x45,
	0x4e, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x55, 0x4e, 0x4e, 0x49,
	0x4e, 0x47, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x46, 0x49, 0x4e, 0x49, 0x53, 0x48, 0x45, 0x44,
	0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x03, 0x12, 0x0c,
	0x0a, 0x08, 0x43, 0x45, 0x4e, 0x43, 0x45, 0x4c, 0x45, 0x44, 0x10, 0x04, 0x2a, 0x56, 0x0a, 0x0e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x57, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x12, 0x10,
	0x0a, 0x0c, 0x50, 0x52, 0x4f, 0x56, 0x49, 0x53, 0x49, 0x4f, 0x4e, 0x49, 0x4e, 0x47, 0x10, 0x00,
	0x12, 0x19, 0x0a, 0x15, 0x50, 0x52, 0x4f, 0x56, 0x49, 0x53, 0x49, 0x4f, 0x4e, 0x49, 0x4e, 0x47,
	0x5f, 0x46, 0x49, 0x4e, 0x49, 0x53, 0x48, 0x45, 0x44, 0x10, 0x01, 0x12, 0x17, 0x0a, 0x13, 0x50,
	0x52, 0x4f, 0x56, 0x49, 0x53, 0x49, 0x4f, 0x4e, 0x49, 0x4e, 0x47, 0x5f, 0x46, 0x41, 0x49, 0x4c,
	0x45, 0x44, 0x10, 0x02, 0x42, 0x06, 0x5a, 0x04, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_ptadmin_proto_rawDescOnce sync.Once
	file_proto_ptadmin_proto_rawDescData = file_proto_ptadmin_proto_rawDesc
)

func file_proto_ptadmin_proto_rawDescGZIP() []byte {
	file_proto_ptadmin_proto_rawDescOnce.Do(func() {
		file_proto_ptadmin_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_ptadmin_proto_rawDescData)
	})
	return file_proto_ptadmin_proto_rawDescData
}

var file_proto_ptadmin_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_ptadmin_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_ptadmin_proto_goTypes = []interface{}{
	(PtTaskType)(0),               // 0: PtTaskType
	(PtLaunchedTaskStatus)(0),     // 1: PtLaunchedTaskStatus
	(StatusWorkflow)(0),           // 2: StatusWorkflow
	(*PtTaskRequestTracffic)(nil), // 3: PtTaskRequestTracffic
	(*PtTaskRequestScript)(nil),   // 4: PtTaskRequestScript
	(*PtTaskRequest)(nil),         // 5: PtTaskRequest
	(*PtLaunchedTask)(nil),        // 6: PtLaunchedTask
	(*PtLaunchedTaskList)(nil),    // 7: PtLaunchedTaskList
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_proto_ptadmin_proto_depIdxs = []int32{
	0,  // 0: PtTaskRequest.type:type_name -> PtTaskType
	3,  // 1: PtTaskRequest.traffics:type_name -> PtTaskRequestTracffic
	4,  // 2: PtTaskRequest.scripts:type_name -> PtTaskRequestScript
	5,  // 3: PtLaunchedTask.task:type_name -> PtTaskRequest
	1,  // 4: PtLaunchedTask.task_status:type_name -> PtLaunchedTaskStatus
	2,  // 5: PtLaunchedTask.provision_status:type_name -> StatusWorkflow
	8,  // 6: PtLaunchedTask.created:type_name -> google.protobuf.Timestamp
	8,  // 7: PtLaunchedTask.finished:type_name -> google.protobuf.Timestamp
	8,  // 8: PtLaunchedTask.last_updated:type_name -> google.protobuf.Timestamp
	6,  // 9: PtLaunchedTaskList.launched_tasks:type_name -> PtLaunchedTask
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_ptadmin_proto_init() }
func file_proto_ptadmin_proto_init() {
	if File_proto_ptadmin_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_ptadmin_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PtTaskRequestTracffic); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ptadmin_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PtTaskRequestScript); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ptadmin_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PtTaskRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ptadmin_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PtLaunchedTask); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ptadmin_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PtLaunchedTaskList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_ptadmin_proto_msgTypes[1].OneofWrappers = []interface{}{}
	file_proto_ptadmin_proto_msgTypes[2].OneofWrappers = []interface{}{}
	file_proto_ptadmin_proto_msgTypes[3].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_ptadmin_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_ptadmin_proto_goTypes,
		DependencyIndexes: file_proto_ptadmin_proto_depIdxs,
		EnumInfos:         file_proto_ptadmin_proto_enumTypes,
		MessageInfos:      file_proto_ptadmin_proto_msgTypes,
	}.Build()
	File_proto_ptadmin_proto = out.File
	file_proto_ptadmin_proto_rawDesc = nil
	file_proto_ptadmin_proto_goTypes = nil
	file_proto_ptadmin_proto_depIdxs = nil
}
