
# Prometheus Monitor Service (Metrics)
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: servicemonitor
    app.kubernetes.io/instance: controller-manager-metrics-monitor
    app.kubernetes.io/component: metrics
    app.kubernetes.io/created-by: pt-operator
    app.kubernetes.io/part-of: pt-operator
    app.kubernetes.io/managed-by: kustomize
  name: controller-manager-metrics-monitor
  namespace: system
spec:
  endpoints:
  - port: metrics
    interval: 15s
  selector:
    matchLabels:
      control-plane: controller-manager
