//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PtTask) DeepCopyInto(out *PtTask) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PtTask.
func (in *PtTask) DeepCopy() *PtTask {
	if in == nil {
		return nil
	}
	out := new(PtTask)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PtTask) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PtTaskList) DeepCopyInto(out *PtTaskList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PtTask, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PtTaskList.
func (in *PtTaskList) DeepCopy() *PtTaskList {
	if in == nil {
		return nil
	}
	out := new(PtTaskList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PtTaskList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PtTaskSpec) DeepCopyInto(out *PtTaskSpec) {
	*out = *in
	if in.Execution != nil {
		in, out := &in.Execution, &out.Execution
		*out = make([]PtTaskSpecExecution, len(*in))
		copy(*out, *in)
	}
	if in.Scenarios != nil {
		in, out := &in.Scenarios, &out.Scenarios
		*out = make(map[string]PtTaskSpecScenario, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PtTaskSpec.
func (in *PtTaskSpec) DeepCopy() *PtTaskSpec {
	if in == nil {
		return nil
	}
	out := new(PtTaskSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PtTaskSpecExecution) DeepCopyInto(out *PtTaskSpecExecution) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PtTaskSpecExecution.
func (in *PtTaskSpecExecution) DeepCopy() *PtTaskSpecExecution {
	if in == nil {
		return nil
	}
	out := new(PtTaskSpecExecution)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PtTaskSpecScenario) DeepCopyInto(out *PtTaskSpecScenario) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PtTaskSpecScenario.
func (in *PtTaskSpecScenario) DeepCopy() *PtTaskSpecScenario {
	if in == nil {
		return nil
	}
	out := new(PtTaskSpecScenario)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PtTaskStatus) DeepCopyInto(out *PtTaskStatus) {
	*out = *in
	if in.Phases != nil {
		in, out := &in.Phases, &out.Phases
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PtTaskStatus.
func (in *PtTaskStatus) DeepCopy() *PtTaskStatus {
	if in == nil {
		return nil
	}
	out := new(PtTaskStatus)
	in.DeepCopyInto(out)
	return out
}
