# permissions for end users to edit pttasks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: pttask-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: pt-operator
    app.kubernetes.io/part-of: pt-operator
    app.kubernetes.io/managed-by: kustomize
  name: pttask-editor-role
rules:
- apiGroups:
  - perftest.com.google.gtools
  resources:
  - pttasks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - perftest.com.google.gtools
  resources:
  - pttasks/status
  verbs:
  - get
