apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: gmp-test-sa@play-api-service.iam.gserviceaccount.com
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: controller-manager-sa
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: pt-operator
    app.kubernetes.io/part-of: pt-operator
    app.kubernetes.io/managed-by: kustomize
  name: controller-manager
  namespace: system
