apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: pt-admin
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '1'
        run.googleapis.com/execution-environment: gen2
        autoscaling.knative.dev/maxScale: '100'
        run.googleapis.com/cpu-throttling: 'false'
    spec:
      containerConcurrency: 10
      timeoutSeconds: 3000
      containers:
      - image: asia-docker.pkg.dev/play-api-service/test-images/pt-admin
        ports:
        - name: http1
          containerPort: 9080
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
        startupProbe:
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 1
          tcpSocket:
            port: 9080
