apiVersion: perftest.com.google.gtools/v1
kind: PtTask
metadata:
  labels:
    app.kubernetes.io/name: pttask
    app.kubernetes.io/instance: pttask-sample
    app.kubernetes.io/part-of: pt-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: pt-operator
  name: pttask-sample
spec:
  type: Local
  execution:
    - executor: locust
      concurrency: 100
      ramp-up: 10s
      hold-for: 5m
      master: True
      workers: 1
      scenario: test-example
  scenarios:
    test-example:
      default-address: http://blazedemo.com
      script: locustfile.py
  images:
    test-example:
      masterImage: asia-docker.pkg.dev/play-api-service/test-images/taurus-base
      workerImage: asia-docker.pkg.dev/play-api-service/test-images/locust-worker
  localDebug:
    ldjson: ./config/samples/locust-workers.ldjson