apiVersion: perftest.com.google.gtools/v1
kind: PtWorker
metadata:
  labels:
    app.kubernetes.io/name: ptworker
    app.kubernetes.io/instance: ptworker-sample
    app.kubernetes.io/part-of: pt-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: pt-operator
  name: ptworker-sample
spec:
  id: df116199-2fa8-4216-a834-903226b61a21
  masterType: Locust
  locustMaster:
    host: 10.33.2.104
    port: 5557
